// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\SARADHM\Downloads\WorkDir\kafka-practice\delivery-tracking-demo\Delivery_Tracking_API\consumer1DB\controller\Icontroller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockControllerInterface is a mock of ControllerInterface interface.
type MockControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockControllerInterfaceMockRecorder
}

// MockControllerInterfaceMockRecorder is the mock recorder for MockControllerInterface.
type MockControllerInterfaceMockRecorder struct {
	mock *MockControllerInterface
}

// NewMockControllerInterface creates a new mock instance.
func NewMockControllerInterface(ctrl *gomock.Controller) *MockControllerInterface {
	mock := &MockControllerInterface{ctrl: ctrl}
	mock.recorder = &MockControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerInterface) EXPECT() *MockControllerInterfaceMockRecorder {
	return m.recorder
}

// FetchAllOrders mocks base method.
func (m *MockControllerInterface) FetchAllOrders(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FetchAllOrders", c)
}

// FetchAllOrders indicates an expected call of FetchAllOrders.
func (mr *MockControllerInterfaceMockRecorder) FetchAllOrders(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllOrders", reflect.TypeOf((*MockControllerInterface)(nil).FetchAllOrders), c)
}

// FetchOrderByKey mocks base method.
func (m *MockControllerInterface) FetchOrderByKey(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FetchOrderByKey", c)
}

// FetchOrderByKey indicates an expected call of FetchOrderByKey.
func (mr *MockControllerInterfaceMockRecorder) FetchOrderByKey(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrderByKey", reflect.TypeOf((*MockControllerInterface)(nil).FetchOrderByKey), c)
}

// InsertOrder mocks base method.
func (m *MockControllerInterface) InsertOrder(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertOrder", c)
}

// InsertOrder indicates an expected call of InsertOrder.
func (mr *MockControllerInterfaceMockRecorder) InsertOrder(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrder", reflect.TypeOf((*MockControllerInterface)(nil).InsertOrder), c)
}
