@Library('dta-shared-jenkins-library@master') _

pipeline{
    agent any
    environment{
        def version =  org.myorg.MyUtility.getVersion()
    }
    stages{
        stage("Build producer"){
            steps{
                bat "docker build -t pardha1024/dta-producer:${version} producer/"
            }
        }
        stage("Build Consumer 1"){
            steps{
                bat "docker build -t pardha1024/dta-consumer1:${version} consumer1/"
            }
        }
        stage("Build BadgerDB 1"){
            steps{
                bat "docker build -t pardha1024/dta-consumer1db:${version} consumer1db/"
            }
        }
        stage("Clean up"){
            steps{
                deleteDir()
            }
        }
    }
}
