pipeline{
    agent any
    stages{
        stage("Build producer"){
            steps{
                bat "docker build -t pardha1024/dta-producer producer/"
            }
        }
        stage("Build Consumer 1"){
            steps{
                bat "docker build -t pardha1024/dta-consumer1 consumer1/"
            }
        }
        stage("Build BadgerDB 1"){
            steps{
                bat "docker build -t pardha1024/dta-consumer1db consumer1db/"
            }
        }
        stage("Upload to Docker HUB"){
            steps{
                bat """
                docker login

                docker push pardha1024/dta-producer

                docker push pardha1024/dta-consumer1

                docker push pardha1024/dta-consumer1db
                """
            }
        }
        stage("Clean up"){
            steps{
                deleteDir()
            }
        }
    }
}