// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\SARADHM\Downloads\practice\delivery-tracking-demo\Delivery_Tracking_API\consumer2\controller\Icontroller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderControllerInterface is a mock of OrderControllerInterface interface.
type MockOrderControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderControllerInterfaceMockRecorder
}

// MockOrderControllerInterfaceMockRecorder is the mock recorder for MockOrderControllerInterface.
type MockOrderControllerInterfaceMockRecorder struct {
	mock *MockOrderControllerInterface
}

// NewMockOrderControllerInterface creates a new mock instance.
func NewMockOrderControllerInterface(ctrl *gomock.Controller) *MockOrderControllerInterface {
	mock := &MockOrderControllerInterface{ctrl: ctrl}
	mock.recorder = &MockOrderControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderControllerInterface) EXPECT() *MockOrderControllerInterfaceMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockOrderControllerInterface) GetOrder(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetOrder", c)
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderControllerInterfaceMockRecorder) GetOrder(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderControllerInterface)(nil).GetOrder), c)
}

// GetStatus mocks base method.
func (m *MockOrderControllerInterface) GetStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetStatus", c)
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockOrderControllerInterfaceMockRecorder) GetStatus(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockOrderControllerInterface)(nil).GetStatus), c)
}
